PIE_CHART = "pie-chart"
YEAR_DROPDOWN = "year-dropdown"
SELECT_ALL_YEARS_BUTTON = "select-all-years-button"
MONTH_DROPDOWN = "month-dropdown"
SELECT_ALL_MONTHS_BUTTON = "select-all-months-button"
SELECT_ALL_CATEGORIES_BUTTON = "select-all-categories-button"
CATEGORY_DROPDOWN = "category-dropdown"
